#!/bin/bash

# Installs stanley ssh keys on the first boot, and deletes itself.
# Copy to /etc/init.d

rm /home/stanley/.ssh/stanley_rsa*

ssh-keygen -f /home/stanley/.ssh/stanley_rsa -P '' && cat /home/stanley/.ssh/stanley_rsa.pub >> /home/stanley/.ssh/authorized_keys && chmod 0600 /home/stanley/.ssh/authorized_keys

chown stanley:stanley /home/stanley/.ssh/*

rm $0
